version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: novobanco-sqlserver
    environment:
      SA_PASSWORD: "1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: ./src/NovoBanco.Api/Dockerfile
    container_name: novobanco-api
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=NovoBancoDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
    ports:
      - "8080:8080"

volumes:
  sqlserver_data:
